# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: 'self-hosted pool'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'FTALive - Registry'
        repository: 'webapi'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
  - job: Publish test collection
    displayName: publish test collection
    pool:
      name: 'self-hosted pool'
    steps:
    - task: CopyFiles@2
      inputs:
        Contents: '*.postman_collection.json'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'tests'
        publishLocation: 'Container'
      
      
